name: Custom Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  custom_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run bat_to_datH5 script
        run: python3 /RVT/utils/bat_to_datH5.py

      - name: Remove gen1_frequenciesgen1_200hz directory
        run: sudo rm -rf /RVT/gen1_frequenciesgen1_200hz/
        # Nota: In un ambiente CI, l'uso di sudo potrebbe richiedere configurazioni specifiche
        # Se sudo non funziona, potresti dover usare alternative o verificare i permessi

